### ISSUE TITLE
Change label for "path on server" on S3 

### ISSUE THREAD

**Issue by kenkendk** [duplicati/ngclient#21]
The "path on server" should be something like "path prefix in bucket"

**Comment by sp90** [comment]
Labels are just forwarded directly from the backend, might be that we should just add a dictionary on top

This is what the old solution is doing so changing the client backend could break the "ngax" client 

I see it as an anti-pattern since our language then depending on these very loose "keys" which are natural language

So let's make it based on the old labels for now and then we could rewrite it "if/when" the ngax client are deprecated

**Comment by kenkendk** [comment]
I don't see the string "Path on server" anywhere in the backend code?
The `ngax` client just has a text label defined in the HTML (the translate attribute flags it for localization).
