### ISSUE TITLE
Remote hosted ngclient can show empty dropdowns (timing issue?)

### ISSUE THREAD

**Issue by kenkendk** [duplicati/ngclient#41]
<img width="716" alt="Screenshot 2024-10-28 at 16 05 41" src="https://github.com/user-attachments/assets/0ec2a8f7-7500-40f4-aeba-fd247a366752">

**Comment by kenkendk** [comment]
It can also happen for other dropdowns, that do not require remote data:
<img width="548" alt="Screenshot 2024-10-28 at 16 07 05" src="https://github.com/user-attachments/assets/cf335cca-198c-4b38-a19f-472567c88e9d">

**Comment by sp90** [comment]
I would say the options with GB seem very unlikely to be timing since it's a constant in the frontend

The encryption could be because it's fetched from the client backend, but this issue might be related

I would need a way to reproduce and currently, I'm unable to could you try to write how to reproduce?
